# Generated by Django 2.0.9 on 2018-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pan_number',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
