# Generated by Django 2.0.9 on 2018-10-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181013_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(null=True),
        ),
    ]
