# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-13 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_start_date', models.DateField(null=True)),
                ('unique_loan_id', models.CharField(max_length=256)),
                ('loan_status', models.CharField(choices=[('APP', 'Application'), ('SUB', 'Submitted'), ('REJ', 'Rejected'), ('ACT', 'Active'), ('FIN', 'Finished'), ('DEL', 'Delinquent')], default='APP', max_length=50)),
                ('total_loan_amount', models.FloatField(null=True)),
                ('down_payment', models.FloatField(null=True)),
                ('months', models.IntegerField(null=True)),
                ('emi', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('credit_score', models.IntegerField()),
                ('apparent_credit_score', models.IntegerField()),
                ('pan_number', models.CharField(max_length=15)),
                ('pan_card_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vouching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vouch_value', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('REQ', 'Requested'), ('REJ', 'Rejected'), ('ACC', 'Accepted')], max_length=50)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouches', to='scoring.LoanApplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouches', to='scoring.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='scoring.UserProfile'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='vouchers',
            field=models.ManyToManyField(related_name='vouched_loan_applications', to='scoring.UserProfile'),
        ),
    ]
